swagger: "2.0"                                  # 基于Swagger 2.0版本实现
info:
  version: v1
  title: 白名单
  description: 白名单相关接口
basePath: /regions/{regionId}
paths:
  "/instances/{instanceId}/whiteList": #实例的IP白名单
    put:
      description: 修改允许访问实例的IP白名单。白名单是允许访问当前实例的IP/IP段列表，缺省情况下，白名单对本VPC开放。如果用户开启了外网访问的功能，还需要对外网的IP配置白名单。
      operationId: modifyWhiteList
      #x-jdcloud-internal: true
      parameters:
        - name: ips
          required: true
          in: query
          type: string
          description: IP或IP段，不同的IP/IP段之间用英文逗号分隔，例如0.0.0.0/0,192.168.0.10
      responses:
        200:
          description: OK
    get:
      description: 查看RDS实例当前白名单。白名单是允许访问当前实例的IP/IP段列表，缺省情况下，白名单对本VPC开放。如果用户开启了外网访问的功能，还需要对外网的IP配置白名单。
      operationId: describeWhiteList
      #x-jdcloud-internal: true
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  whiteLists:
                    type: array
                    description: 白名单列表
                    items:
                      $ref: ../model/WhiteList.yaml#/definitions/WhiteList
#路径通用参数
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: 地域代码，取值范围参见[《各地域及可用区对照表》](../Enum-Definitions/Regions-AZ.md)
  instanceId:
    name: instanceId
    in: path
    required: true
    type: string
    description: RDS 实例ID，唯一标识一个RDS实例