swagger: "2.0"
definitions:
  Backup:
    x-jdcloud-module: rds
    title: Backup
    type: object
    properties:
      backupId:
        type: string
        description: 备份ID
      backupName:
        type: string
        description: 备份名称，最长支持64个英文字符或等长的中文字符
      instanceId:
        type: string
        description: 备份所属实例ID
      backupStatus:
        type: string
        description: 备份状态，请查看[枚举参数定义](../Enum-Definitions/Enum-Definitions.md)
      backupStartTime:
        type: string
        description: 备份开始时间，格式为：YYYY-MM-DD HH:mm:ss
      backupEndTime:
        type: string
        description: 备份结束时间，格式为：YYYY-MM-DD HH:mm:ss<br>- **SQL Server支持**<br>- **MySQL不支持**
      backupType:
        type: string
        description: 备份类型，全量备份或增量备份，请查看[枚举参数定义](../Enum-Definitions/Enum-Definitions.md)<br>- **SQL Server支持**<br>- **MySQL不支持**
      backupMode:
        type: string
        description: 备份模式，系统自动备份或手动备份，请查看[枚举参数定义](../Enum-Definitions/Enum-Definitions.md)
      backupUnit:
        type: string
        description: 备份粒度，实例备份或者多库备份，请查看[枚举参数定义](../Enum-Definitions/Enum-Definitions.md)<br>- **SQL Server支持**<br>- **MySQL不支持**
      backupFiles:
        type: array
        items:
          type: string
          description: 备份文件名称
        description: 备份文件列表<br>- **SQL Server支持**,备份可以有多个文件，文件名的命名规则为:<br>（1）全备：数据库名+.bak<br>（2）增量：数据库名+.diff<br>- **MySQL不支持**
      backupSizeByte:
        type: integer
        description: 整个备份集大小，单位：Byte