swagger: "2.0"
definitions:
  DDosAttackLog:
    type: object
    x-jdcloud-module: ipanti
    properties:
      attackTraffic:
        type: number
        format: float
        description: 攻击流量大小
      blackHole:
        type: integer
        description: 是否触发黑洞，0否 1是
      startTime:
        type: string
        description: 攻击开始时间
      endTime:
        type: string
        description: 攻击结束时间
      unit:
        type: string
        description: 流量单位，bps、Kbps、Mbps、Gbps
      instanceId:
        type: integer
        format: int64
        description: 高防实例id
      name:
        type: string
        description: 高防实例名称