swagger: "2.0"
definitions:
  forwardRuleSpec:
    type: object
    x-jdcloud-module: ipanti
    properties:
      protocol:
        type: string
        description: 协议：TCP或者UDP
      port:
        type: integer
        description: 端口号
      algorithm:
        type: string
        description: 转发规则：wrr->带权重的轮询，wlc->加权最小连接，rr->不带权重的轮询，sh->源地址hash
      originType:
        type: string
        description: 回源类型，ip或者domain
      originAddr:
        type: array
        items:
          $ref: "../model/OriginAddrItem.yaml#/definitions/OriginAddrItem"
      onlineAddr:
        type: array
        items:
          type: string
      originDomain:
        type: string
        description: 回源域名
      originPort:
        type: integer
        description: 回源端口号