swagger: "2.0"
info:
  version: "v1"
  title: Acl
  description: Acl相关接口

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/networkAcls/":
    get:
      summary: "查询Acl列表"
      description: "查询Acl列表"
      operationId: describeNetworkAcls
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          minimum: 1
          description: 页码, 默认为1, 取值范围：[1,∞), 页码超过总页数时, 显示最后一页
        - name: pageSize
          in: query
          type: integer
          default: 20
          minimum: 10
          maximum: 100
          description: 分页大小，默认为20，取值范围：[10,100]
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
            description: |
                   networkAclIds - 弹性网卡ID列表，支持多个
                   networkAclNames - 弹性网卡名称列表，支持多个
                   vpcId - 弹性网卡所属vpc Id，支持单个
                 
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                description: "返回结果"
                properties:
                  networkAcls:
                    description: "networkAcl资源信息列表"
                    type: array
                    items:
                      $ref: "../model/NetworkAcl.yaml#/definitions/networkAcl"
                  totalCount:
                    description: "总数量"
                    type: number
              requestId:
                description: "请求ID"
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        429:
          description: "Quota exceeded"
        500:
          description: "Internal error"


    post:
      description: "创建networkAcl接口"
      operationId: CreateNetworkAcl
      parameters:
        - name: networkAclSpec
          in: body
          required: true
          description: "创建networkAcl请求参数"
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/NetworkAclSpec.yaml#/definitions/networkAclSpec"
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              result:
                description: "返回结果"
                properties:
                  networkAclId:
                    description: "networkAcl ID"
                    type: string
              requestId:
                description: "请求ID"
                type: string
        400:
          description: "Invalid parameter"
        404:
          description: "Not found"
        429:
          description: "Quota exceeded"
        500:
          description: "Internal error"


  "/networkAcls/{networkAclId}":
    get:
      summary: "查询networkAcl信息详情"
      description: "查询networkAcl资源详情"
      operationId: describeNetworkAcl
    
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                description: "返回结果"
                properties:
                  networkAcl:
                    description: "networkAcl资源信息"
                    $ref: "../model/NetworkAcl.yaml#/definitions/networkAcl"
              requestId:
                description: "请求ID"
                type: string
    
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal error"

    
    delete:
      summary: "删除networkAcl"
      description: "删除networkAcl接口"
      operationId: deleteNetworkAcl
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                description: "请求ID"
                type: string
        404:
          description: NOT_FOUND
        500:
          description: Internal error
        
    
    patch:
      summary: "修改networkAcl"
      description: "修改networkAcl接口"
      operationId: modifyNetworkAcl
      parameters:
        - name: modifyNetworkAclSpec
          in: body
          required: true
          description: "修改networkAcl属性"
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/ModifyNetworkAclSpec.yaml#/definitions/modifyNetworkAclSpec"
    
      responses:
        200:
          description: OK
          schema:
            properties:
              requestId:
                description: "请求ID"
                type: string
        400:
          description: "Invalid parameter"
        404:
          description: "Not found"
        500:
          description: "Internal error"


  "/networkAcls/{networkAclId}:associateNetworkAcl":
    post:
      description: "给子网绑定networkAcl接口"
      operationId: associateNetworkAcl
      parameters:
        - name: subnetIds
          in: body
          required: true
          description: "修改networkAcl属性"
          schema:
            type: array
            items:
              type: string
          
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              requestId:
                description: "请求ID"
                type: string
        400:
          description: "Invalid parameter"
        404:
          description: "Not found"
        500:
          description: "Internal error"


  "/networkAcls/{networkAclId}:disassociateNetworkAcl":
    post:
      description: "给子网解绑NetworkAcl接口"
      operationId: disassociateNetworkAcl
      parameters:
        - name: subnetId
          in: query
          type: string
          required: true
          description: networkAcl要解绑的子网ID

      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                description: "请求ID"
                type: string
        400:
          description: "Invalid parameter"
        404:
          description: "Not found"
        500:
          description: "Internal error"


  "/networkAcls/{networkAclId}:addNetworkAclRules":
    post:
      description: "添加networkAcl规则接口"
      operationId: addNetworkAclRules
      parameters:
        - name: addNetworkAclRulesSpec
          in: body
          required: true
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/AddNetworkAclRulesSpec.yaml#/definitions/addNetworkAclRulesSpec"
      
      responses:
        200:
          description: Successful operation
          schema:
            type: object
            properties:
              requestId:
                description: "请求ID"
                type: string
        400:
          description: "Invalid parameter"
        404:
          description: "Not found"
        429:
          description: "Quota exceeded"
        500:
          description: "Internal error"

    
  "/networkAcls/{networkAclId}:removeNetworkAclRules":
    post:
      description: "移除networkAcl规则"
      operationId: removeNetworkAclRules
      parameters:
        - name: ruleIds
          in: body
          required: true
          description: "修改networkAcl属性"
          schema: 
            type: array
            items:
              type: string
      
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                description: "请求ID"
                type: string
        400:
          description: "Invalid parameter"
        404:
          description: "Not found"
        500:
          description: "Internal error"


  "/networkAcls/{networkAclId}:modifyNetworkAclRules":
    post:
      description: "修改networkAcl接口"
      operationId: modifyNetworkAclRules
      parameters:
        - name: modifyNetworkAclRulesSpec
          in: body
          required: true
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/ModifyNetworkAclRules.yaml#/definitions/modifyNetworkAclRulesSpec"
      
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                 description: "请求ID"
                 type: string
        400:
          description: "Invalid parameter"
        404:
          description: "Not found"
        500:
          description: "Internal error"


parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  networkAclId:
    name: networkAclId
    in: path
    required: true
    type: string
    description: networkAclId ID