swagger: "2.0"
info:
  version: "v1"
  title: 路由表
  description: 路由表相关接口

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/routeTables/":
     get:
       summary: "查询路由表列表"
       description: "查询路由表列表"
       operationId: describeRouteTables
       parameters:
         - name: pageNumber
           in: query
           type: integer
           default: 1
           minimum: 1
           description: 页码, 默认为1, 取值范围：[1,∞), 页码超过总页数时, 显示最后一页
         - name: pageSize
           in: query
           type: integer
           default: 20
           minimum: 10
           maximum: 100
           description: 分页大小，默认为20，取值范围：[10,100]
         - name: filters
           in: query
           type: array
           items:
             $ref: "../../common/model/Filter.yaml#/definitions/filter"
           description: |
                  routeTableIds - 路由表ID列表，支持多个
                  routeTableNames - 路由表名称列表，支持多个
                  vpcId	- 路由表所属vpc Id，支持单个

       responses:
         200:
           description: OK
           schema:
             properties:
               result:
                 description: "返回结果"
                 properties:
                   routeTables:
                     description: "路由表资源信息列表"
                     type: array
                     items:
                       $ref: "../model/RouteTable.yaml#/definitions/routeTable"
                   totalCount:
                     description: "总数量"
                     type: number
               requestId:
                 description: "请求ID"
                 type: string
         400:
            description: "invalid parameter"
         401:
            description: "Authentication failed"

     #create routeTable
     post:
       summary: "创建路由表"
       description: "创建路由表"
       operationId: createRouteTable
       parameters:
         - name: routeTableSpec
           in: body
           required: true
           description: "创建路由表请求参数"
           x-jdcloud-tiered: false
           schema:
             $ref: "../model/RouteTableSpec.yaml#/definitions/routeTableSpec"

       responses:
         200:
           description: OK
           schema:
             properties:
               result:
                 description: "返回结果"
                 properties:
                   routeTableId:
                     description: "路由表ID"
                     type: string
               requestId:
                 description: "请求ID"
                 type: string
         400:
            description: "invalid parameter"
         404:
            description: "Resource not found"
         500:
            description: "Internal server error"


  "/routeTables/{routeTableId}":
     #describe routeTable
     get:
       summary: 查询路由表信息详情
       description: 查询路由表信息详情
       operationId: describeRouteTable
       responses:
         200:
           description: OK
           schema:
             properties:
               result:
                 description: "返回结果"
                 properties:
                   routeTable:
                      description: "路由表资源信息"
                      $ref: "../model/RouteTable.yaml#/definitions/routeTable"
               requestId:
                 description: "请求ID"
                 type: string
         400:
            description: "invalid parameter"
         401:
            description: "Authentication failed"

     #modify routeTable
     patch:
       summary: 修改路由表属性
       description: 修改路由表属性
       operationId: modifyRouteTable
       parameters:
         - name: modifyRouteTableSpec
           in: body
           required: true
           description: "修改路由表"
           x-jdcloud-tiered: false
           schema:
             $ref: "../model/ModifyRouteTableSpec.yaml#/definitions/modifyRouteTableSpec"
       responses:
         200:
           description: OK
           schema:
             properties:
               requestId:
                 description: "请求ID"
                 type: string
         400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
         404:
           description: Resource not found

     #delete routeTable
     delete:
         summary: 删除路由表
         description: 删除路由表
         operationId: deleteRouteTable
         responses:
           200:
             description: OK
             schema:
               properties:
                 requestId:
                   description: "请求ID"
                   type: string
           400:
             description: invalid parameter
           404:
             description: Resource not found
           500:
             description: Internal server error

  #add routeTable rules
  "/routeTables/{routeTableId}:addRouteTableRules":
    post:
      summary: "添加路由表规则"
      description: "添加路由表规则"
      operationId: addRouteTableRules
      parameters:
        - name: addRouteTableRulesSpec
          in: body
          required: true
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/AddRouteTableRulesSpec.yaml#/definitions/addRouteTableRulesSpec"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                 description: "请求ID"
                 type: string
        400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
        404:
           description: Resource not found
        409:
           description: RouteTable rules not in the same vpc
        500:
           description: Internal server error

  #remove routeTable rules
  "/routeTables/{routeTableId}:removeRouteTableRules":
    post:
      summary: "移除路由表规则"
      description: "移除路由表规则"
      operationId: removeRouteTableRules
      parameters:
        - in: body
          name: ruleIds
          description: 路由表规则Id列表
          required: true
          schema:
            type: array
            items:
              type: string

      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                 description: "请求ID"
                 type: string
        400:
           description: "Request field x.y.z is missing."
        404:
           description: "Target 'xxx' not found; TargetGroup 'xxx' not found."
        500:
           description: "internal server error"
  
  #modify routeTable rules         
  "/routeTables/{routeTableId}:modifyRouteTableRules":
    post:
      summary: "修改路由表规则"
      description: "修改路由表规则"
      operationId: modifyRouteTableRules
      parameters:
        - name: modifyRouteTableRulesSpec
          in: body
          required: true
          x-jdcloud-tiered: false
          schema:
            $ref: "../model/ModifyRouteTableRulesSpec.yaml#/definitions/modifyRouteTableRulesSpec"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: object
            properties:
              requestId:
                 description: "请求ID"
                 type: string
        400:
           description: "invalid parameter"
        404:
           description: "RouteTable or RouteTableRule not found"
        500:
           description: Internal server error
           
  "/routeTables/{routeTableId}:associateRouteTable":
     post:
       description: "路由表绑定子网接口"
       operationId: associateRouteTable
       parameters:
         - name: associateRouteTableSpec
           in: body
           required: true
           x-jdcloud-tiered: false
           schema:
             $ref: "../model/AssociateRouteTableSpec.yaml#/definitions/associateRouteTableSpec"
       responses:
         200:
           description: Successful operation
           schema:
             type: object
             properties:
               requestId:
                 description: "请求ID"
                 type: string
         400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
         404:
           description: Resource not found

  "/routeTables/{routeTableId}:disassociateRouteTable":
     post:
       description: "给路由表解绑子网接口"
       operationId: disassociateRouteTable
       parameters:
         - name: disassociateRouteTableSpec
           in: body
           required: true
           x-jdcloud-tiered: false
           schema:
             $ref: "../model/DisassociateRouteTableSpec.yaml#/definitions/disassociateRouteTableSpec"
       responses:
         200:
           description: "Successful operation"
           schema:
             type: object
             properties:
               requestId:
                 description: "请求ID"
                 type: string
         400:
           description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
         404:
           description: Resource not found

parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  routeTableId:
    name: routeTableId
    in: path
    required: true
    type: string
    description: RouteTable ID
