swagger: "2.0"
info:
  version: "v1"
  title: 子网
  description: 子网相关接口

basePath: /regions/{regionId}

schemes:
  - https

paths:
  "/subnets/":
     #describe subnets
     get:
       summary: "查询子网列表"
       description: "查询子网列表"
       operationId: describeSubnets

       parameters:
          - name: pageNumber
            in: query
            type: integer
            default: 1
            minimum: 1
            description: 页码, 默认为1, 取值范围：[1,∞), 页码超过总页数时, 显示最后一页
          - name: pageSize
            in: query
            type: integer
            default: 20
            minimum: 10
            maximum: 100
            description: 分页大小，默认为20，取值范围：[10,100]

          - name: filters
            in: query
            type: array
            items:
              #$ref: "/jcloud-open-api/common/model/Filter.yaml#/definitions/filter"
              $ref: "../../common/model/Filter.yaml#/definitions/filter"
            description: |
                   subnetIds - subnet ID列表，支持多个
                   subnetNames - subnet名称列表，支持多个
                   routeTableId	- 子网关联路由表Id，支持单个
                   aclId - 子网关联acl Id，支持单个
                   vpcId - 子网所属VPC Id，支持单个

       responses:
         200:
           description: OK
           schema:
             properties:
               result:
                 description: "返回结果"
                 properties:
                   subnets:
                     description: "子网资源信息列表"
                     type: array
                     items:
                       $ref: "../model/Subnet.yaml#/definitions/subnet"
                   totalCount:
                     description: "总数量"
                     type: number
               requestId:
                 description: "请求ID"
                 type: string
  
     post:
       summary: "创建子网"
       description: "创建子网"
       operationId: createSubnet
       parameters:
         - name: subnetSpec
           in: body
           required: true
           description: "申请创建子网资源的信息"
           x-jdcloud-tiered: false
           schema:
             $ref: "../model/SubnetSpec.yaml#/definitions/subnetSpec"
       responses:
         200:
           description: Successful operation
           schema:
             type: object
             properties:
               result:
                 description: "返回结果"
                 properties:
                   subnetId:
                     description: "子网ID"
                     type: string
               requestId:
                 description: "请求ID"
                 type: string
         400:
           description: "Invalid parameter"
         401:
           description: "Authentication failed"
         404:
           description: "Not found"
         409:
           description: "Parameter conflict"
         429:
           description: "Quota exceeded"
         500:
           description: "Internal server error"
         503:
           description: "Service unavailable"

  "/subnets/{subnetId}":
      #describe subnet
      get:
        summary: 查询子网信息详情
        description: 查询子网信息详情
        operationId: describeSubnet

        responses:
          200:
            description: OK
            schema:
              properties:
                result:
                  description: "返回结果"
                  properties:
                    subnet:
                      description: "子网资源信息"
                      $ref: "../model/Subnet.yaml#/definitions/subnet"
                requestId:
                  description: "请求ID"
                  type: string

      patch:
        summary: "修改子网"
        description: "修改子网接口"
        operationId: modifySubnet
        parameters:
          - name: modifySubnetSpec
            in: body
            required: true
            description: "修改子网"
            x-jdcloud-tiered: false
            schema:
              $ref: "../model/ModifySubnetSpec.yaml#/definitions/modifySubnetSpec"

        responses:
          200:
            description: OK
            schema:
              properties:
                requestId:
                  description: "请求ID"
                  type: string
          400:
            description: Request parameter x.y.z is 'xxx', expected one of [yyy,zzz]
          404:
            description: Resource not found

      delete:
        summary: "删除子网"
        description: "删除子网"
        operationId: deleteSubnet
        responses:
          200:
            description: OK
            schema:
              properties:
                requestId:
                  description: "请求ID"
                  type: string
          400:
            description: "Invalid parameter"
          401:
            description: "Authentication failed"
          404:
            description: "Not found"
          409:
            description: "Parameter conflict" 
          500:
            description: "Internal server error"
          503:
            description: "Service unavailable"


parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID
  subnetId:
    name: subnetId
    in: path
    required: true
    type: string
    description: Subnet ID
