swagger: "2.0"
definitions:
  cacheInstanceSpec:
    x-jdcloud-module: redis
    required:
      - vpcId
      - subnetId
      - cacheInstanceClass
      - cacheInstanceName
      - azId
    properties:
      vpcId:
        type: string
        description: 缓存redis实例所属的私有网络ID
      subnetId:
        type: string
        description: 缓存redis实例在私有网络下所属的子网ID
      cacheInstanceName:
        type: string
        description: 缓存redis实例名称，只支持数字、字母、英文下划线、中文，且不少于2字符不超过32字符
      cacheInstanceClass:
        type: string
        description: 缓存redis实例规格代码，参见实例规格代码表<a href="https://www.jdcloud.com/help/detail/411/isCatalog/1">实例规格代码</a>。
      password:
        type: string
        description: 密码，为空即为免密，包含且只支持字母及数字，不少于8字符不超过16字符
      azId:
        $ref: "./AzIdSpec.yaml#/definitions/azIdSpec"
        description: 缓存Redis实例所在区域可用区ID信息
      cacheInstanceDescription:
        type: string
        description: 缓存Redis实例描述，不能超过256个字符
      
