swagger: "2.0"
definitions:
  metricDetail:
    x-jdcloud-module: monitor
    type: object
    title: MetricDetail
    properties:
      calculateUnit:
        type: string
        description: 指标的计算单位，比如bit/s、%、byte等
      metric:
        type: string
        description: 监控指标英文标识
      metricName:
        type: string
        description: 监控指标名称
      serviceCode:
        type: string
        description: 资源类型标识
      downSample:
        description: 取样频次
        type: string

  ServiceCodeMetrics:
    x-jdcloud-module: monitor  
    type: object
    properties:
      metrics:
        type: array
        items:
          $ref: '#/definitions/metricDetail'
      serviceCode:
        type: string
        x-go-name: ServiceCode