  name: DevOps
  href: 
  items:
  - name: 产品简介
    items:
      - name: DevOps概述
        href: Introduction/Product-Overview.md
      - name: 核心概念
        href: Introduction/Core-Concepts.md
      - name: 基础架构
        href: Introduction/Basic-Infrastructure.md
      - name: 产品优势
        href: Introduction/Benefits.md
      - name: 产品功能
        href: Introduction/Features.md
      - name: 产品规格
        href: Introduction/Specification.md
      - name: 限制说明
        href: Introduction/Restrictions.md
      - name: 应用场景 
        href: Introduction/Application-Scenarios.md    
  - name: 产品定价
    items:
      - name: 计费概述
        href: Pricing/Billing-Overview.md
      - name: 计费规则
        href: Pricing/Billing-Rules.md
      - name: 价格总览
        href: Pricing/Price-Overview.md
      - name: 购买流程
        href: Pricing/Purchase-Process.md 
      - name: 续费流程
        href: Pricing/Renew-Process.md
  - name: 入门指南
    items:
      - name: 入门指南概述
        href: Getting-Started/Getting-started.md
      - name: 在云主机中安装超级Agent
        href: Getting-Started/Install-Agent.md
      - name: 创建服务树节点
        href: Getting-Started/Create-Instance.md
      - name: 导入京东云主机
        href: Getting-Started/Import-Source.md
      - name: 创建构建任务
        href: Getting-Started/Create-Compilejob.md
      - name: 配置线上发布
        href: Getting-Started/Config-Deployment.md
      - name: 查看基础监控
        href: Getting-Started/Base-Monitor.md
  - name: 操作指南
    items:
      - name: 使用须知
        href: Operation-Guide/Operation-Instruction.md
      - name: 了解DevOps主界面
        href: Operation-Guide/Introduction-index.md
      - name: 配置管理
        href: Operation-Guide/Configuration-Management.md
      - name: 持续交付
        href: Operation-Guide/CICD.md
      - name: 智能监控
        href: Operation-Guide/Monitoring.md
      - name: 运维工具
        href: Operation-Guide/Operation-Task.md
      - name: 账户管理
        href: Operation-Guide/Account-management.md
  - name: 最佳实践
    items:
    - name: 持续交付
      href: Best-Practices/CICD.md
    - name: 智能监控
      href: Best-Practices/Monitoring.md
  - name: 教程
    items:
  - name: 问题排查
    items:
    - name: 故障类问题
      href: Troubleshooting/Troubleshooting.md
    - name: 配置类问题
      href: Troubleshooting/Configuration.md
  - name: 常见问题
    href: FAQ/FAQ.md
  - name: API参考
    href: API/API-Reference.md
  - name: SDK参考
    href: SDK/SDK-Reference.md
  - name: 用户协议
    items:
    - name: 服务条款
      href: User-Agreements/Product-Terms-of-Service.md                 
    - name: SLA
      href: User-Agreements/SLA.md               
  - name: 相关资源
    items:
    - name: 文档历史记录
      href: Related-Resources/Document-History.md   
    - name: 备案
      href: Related-Resources/Filing.md                 
    - name: 词汇表
      href: Related-Resources/Glossary.md           
