swagger: "2.0"
definitions:
  quota:
    x-jdcloud-module: jke
    properties:
      resourceType:
        type: string
        description: 资源类型[kubernetes]
      limit:
        type: integer
        description: 可用资源上限
      used:
        type: integer
        description: 已用资源数量