swagger: '2.0'
info:
  description: 图片样式API
  version: v1
  title: 图片样式相关接口
basePath: '/regions/{regionId}/buckets/{bucketName}'
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: 区域ID
  bucketName:
    name: bucketName
    in: path
    required: true
    type: string
    description: Bucket名称
tags:
  - name: ImageStyle
    description: 图片样式
paths:
  '/imageStyles':
    get:
      tags:
        - ImageStyle
      description: 图片样式列表
      operationId: listImageStyle
      parameters:
        - name: styleName
          in: query
          description: 按样式名称查询
          type: string
        - name: pageNumber
          in: query
          description: 数据页码
          type: integer
          default: 1
        - name: pageSize
          in: query
          description: 每页数据的条数
          type: integer
          default: 10
      responses:
        '200':
          description: success
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: string
              result:
                $ref: '#/definitions/ImageStyleQueryResult'
    post:
      tags:
        - ImageStyle
      description: 添加图片样式
      operationId: createImageStyle
      parameters:
        - name: imageStyle
          in: body
          description: 样式参数
          x-jdcloud-tiered: false
          schema:
            $ref: '#/definitions/ImageStyle'
      responses:
        '200':
          description: success
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: string
              result:
                $ref: '#/definitions/ImageStyleID'
                
  '/imageStyles/{id}':
    parameters:
      - name: id
        in: path
        type: integer
        format: int64
        required: true
        description: 图片样式id
    get:
      tags:
        - ImageStyle
      description: 图片样式详情
      operationId: getImageStyle
      responses:
        '200':
          description: successful operation
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: string
              result:
                $ref: '#/definitions/ImageStyle'
    delete:
      tags:
        - ImageStyle
      description: 删除图片样式
      operationId: deleteImageStyle
      responses:
        '200':
          description: successful operation
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: string
    put:
      tags:
        - ImageStyle
      description: 修改图片样式
      operationId: updateImageStyle
      parameters:
        - name: imageStyle
          in: body
          description: 要修改的样式参数
          x-jdcloud-tiered: false
          schema:
            $ref: '#/definitions/ImageStyle'
      responses:
        '200':
          description: successful operation
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: string
                
  '/imageStyles/count':
    get:
      tags:
        - ImageStyle
      description: 图片样式总数
      operationId: countImageStyle
      parameters:
        - name: styleName
          in: query
          description: 按样式名称查询
          type: string
      responses:
        '200':
          description: success
          x-jdcloud-tiered: false
          schema:
            properties:
              requestId:
                type: string
              result:
                $ref: '#/definitions/ImageStyleCount'
definitions:
  ImageStyle:
    x-jdcloud-module: mps
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: 图片样式id
        readOnly: true
      ucUserId:
        type: string
        description: 用户id
        readOnly: true
      styleName:
        type: string
        description: 图片样式名称
      params:
        type: string
        description: 图片样式参数
      paramAlias:
        type: string
        description: 图片样式参数别名
      regionId:
        type: string
        description: 所属区域
        readOnly: true
      bucketName:
        type: string
        description: 所属Bucket
        readOnly: true
      status:
        type: integer
        format: byte
        description: 图片样式状态
        default: 1
      modifyTime:
        type: string
        format: date
        description: 修改时间
        readOnly: true
      createdTime:
        type: string
        format: date
        description: 创建时间
        readOnly: true
        
  ImageStyleQueryResult:
    x-jdcloud-module: mps
    type: object
    properties:
      styleName:
        description: 按样式名称查询
        type: string
      pageNumber:
        description: 数据页码
        type: integer
        default: 1
      pageSize:
        description: 每页数据的条数
        type: integer
        default: 10
      imageStyleList:
        type: array
        description: 图片样式列表
        items:
          $ref: '#/definitions/ImageStyle'
          
  ImageStyleID:
    x-jdcloud-module: mps
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: 图片样式ID
        
  ImageStyleCount:
    x-jdcloud-module: mps
    type: object
    properties:
      styleCount:
        type: integer
        description: 图片样式总数
schemes:
  - http
