swagger: "2.0"
definitions:
  resultMsg:
    x-jdcloud-module: iam
    properties:
      errorCode:
        type: string
        description: 错误编码
      errorMsg:
        type: string
        description: 错误信息