swagger: "2.0"
definitions:
  sendSingleMsg:
    x-jdcloud-module: iam
    required:
      - templateId
      - templateParam
      - smsMessageSource
      - pin
      - mobileNum
    properties:
      templateId:
        type: integer
        description: 模版code
      templateParam:
        type: array
        items:
          type: string
        description: 模版参数
      smsMessageSource:
        type: string
        description: 业务编码(和产品申请)
      pin:
        type: string
        description: 用户pin
      mobileNum:
        type: string
        description: 手机号