swagger: "2.0"
info:
  version: "v1"
  title: 启动模板
  description: 与启动模板相关的接口

basePath: /regions/{regionId}

paths:
  "/instanceTemplates":
    ###################### 创建启动模板接口 ######################
    post:
      description: |
        创建一个指定参数的启动模板，启动模板中包含创建云主机时的大部分配置参数，避免每次创建云主机时的重复性工作。<br>
        如果是使用启动模板创建云主机，如果指定了某些参数与模板中的参数相冲突，那么新指定的参数会替换模板中的参数。<br>
        如果是使用启动模板创建云主机，如果指定了镜像ID与模板中的镜像ID不一致，那么模板中的dataDisks参数会失效。<br>
        如果使用高可用组(Ag)创建云主机，那么Ag所关联的模板中的参数都不可以被调整，只能以模板为准。
      operationId: createInstanceTemplate
      x-jdcloud-internal: true
      parameters:
        - name: instanceTemplateData
          in: body
          required: true
          description: 启动模板的数据
          schema:
            $ref: "../model/InstanceTemplateSpec.yaml#/definitions/instanceTemplateSpec"
        - name: name
          in: query
          type: string
          required: true
          description: 启动模板的名称，<a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1">参考公共参数规范</a>。
        - name: description
          in: query
          type: string
          description: 启动模板的描述，<a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1">参考公共参数规范</a>。
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  instanceTemplateId:
                    type: string
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        429:
          description: "Quota exceeded"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### 启动模板列表接口 ######################
    get:
      description: |
        查询启动模板列表
      operationId: describeInstanceTemplates
      x-jdcloud-internal: true
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          description: "页码；默认为1"
        - name: pageSize
          in: query
          type: integer
          default: 20
          description: "分页大小；默认为20；取值范围[10, 100]"
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: |
            name - 启动模板名称，模糊匹配，支持多个
            instanceTemplateId - 启动模板ID，精确匹配，支持多个
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  instanceTemplates:
                    type: array
                    items:
                      $ref: "../model/InstanceTemplate.yaml#/definitions/instanceTemplate"
                  totalCount:
                    type: number
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/instanceTemplates/{instanceTemplateId}":
    ###################### 启动模板详情接口 ######################
    get:
      description: |
        查询启动模板详情
      operationId: describeInstanceTemplate
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                $ref: "../model/InstanceTemplate.yaml#/definitions/instanceTemplate"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### 删除启动模板接口 ######################
    delete:
      description: |
        删除一个启动模板
      operationId: deleteInstanceTemplate
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### 修改启动模板信息接口 ######################
    patch:
      description: |
        修改一个启动模板的信息，包括名称、描述
      operationId: updateInstanceTemplate
      x-jdcloud-internal: true
      parameters:
        - name: description
          in: query
          type: string
          description: 模板描述，<a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1">参考公共参数规范</a>。
        - name: name
          in: query
          type: string
          description: 模板名称，<a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1">参考公共参数规范</a>。
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"


  "/instanceTemplates/{instanceTemplateId}:verify":
    ###################### 校验启动模板是否可用接口 ######################
    get:
      description: |
        校验启动模板的有效性
      operationId: verifyInstanceTemplate
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"


#路径通用参数
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: 地域ID
  instanceTemplate:
    name: instanceTemplateId
    in: path
    required: true
    type: string
    description: 启动模板ID
