swagger: "2.0"
info:
  version: "v1"
  title: SSH密钥对
  description: 关于SSH密钥对的相关接口

basePath: /regions/{regionId}

paths:
  "/keypairs":
    ###################### 创建ssh密钥对 ######################
    post:
      description: |
        创建ssh密钥对。公钥部分存储在京东云，并返回未加密的 PEM 编码的 PKCS#8 格式私钥，您只有一次机会保存您的私钥。请妥善保管。<br>
        若传入已存在的密钥名称，会返回错误。
      operationId: createKeypair
      x-jdcloud-internal: true
      parameters:
        - name: keyName
          type: string
          in: query
          required: true
          description: |
            密钥对名称，需要全局唯一。<a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1">参考公共参数规范</a>。
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  keyName:
                    type: string
                    description: 密钥对名称
                  privateKey:
                    type: string
                    description: 密钥对的私钥部分，PEM PKCS#8 格式。
                  keyFingerprint:
                    type: string
                    description: 密钥对的指纹，根据 RFC4716 定义的公钥指纹格式，采用 MD5 信息摘要算法。
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"  
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### 查询ssh密钥对列表 ######################
    get:
      description: |
        批量查询密钥对。<br>
        此接口支持分页查询，默认每页20条。
      operationId: describeKeypairs
      x-jdcloud-internal: true
      parameters:
        - name: pageNumber
          in: query
          type: integer
          default: 1
          description: 页码；默认为1
        - name: pageSize
          in: query
          type: integer
          default: 20
          description: 分页大小；默认为20；取值范围[10, 100]
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: |
            keyNames - 密钥对名称，精确匹配，支持多个
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  keypairs:
                    type: array
                    items:
                      $ref: "../model/Keypair.yaml#/definitions/keypair"
                  totalCount:
                    type: number
                    description: 总的数据条数
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/keypairs:import":
    ###################### 导入ssh密钥对 ######################
    post:
      description: |
        导入由其他工具生成的密钥对的公钥部分。<br>
        若传入已存在的密钥名称，会返回错误。
      operationId: importKeypair
      x-jdcloud-internal: true
      parameters:
        - name: keyName
          in: query
          type: string
          required: true
          description: |
            密钥对名称，需要全局唯一。<a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1">参考公共参数规范</a>。
        - name: publicKey
          in: query
          type: string
          required: true
          description: 密钥对的公钥部分
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  keyName:
                    type: string
                    description: 密钥对名称
                  keyFingerprint:
                    type: string
                    description: 密钥对的指纹，根据 RFC4716 定义的公钥指纹格式，采用 MD5 信息摘要算法。
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

  "/keypairs/{keyName}":
    ###################### 删除ssh密钥对 ######################
    delete:
      description: |
        删除ssh密钥对。
      operationId: deleteKeypair
      x-jdcloud-internal: true
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

#路径通用参数
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: 地域ID
  keyName:
    name: keyName
    in: path
    required: true
    type: string
    description: 密钥名称
