swagger: "2.0"
info:
  version: "v1"
  title: 配额
  description: 与配额相关的接口

basePath: /regions/{regionId}

paths:
  "/quotas":
    ###################### 查询Quota ######################
    get:
      description: |
        查询配额，支持：云主机、镜像、密钥、模板
      operationId: describeQuotas
      parameters:
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: | 
            resourceTypes - 资源类型，支持多个[instance，keypair，image，instanceTemplate]
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  quotas:
                    type: array
                    description: 配额列表
                    items:
                      $ref: "../model/Quota.yaml#/definitions/quota"
              requestId:
                type: string
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

    ###################### 修改Quota ######################
    patch:
      description: |
        修改配额，此接口为内部接口，支持：云主机、镜像、密钥、模板
      operationId: modifyQuota
      x-jdcloud-internal: true
      parameters:
        - name: resourceType
          in: query
          type: string
          description: 资源类型[instance，keypair，image，instanceTemplate]
        - name: limit
          in: query
          type: integer
          description: 配额上限
      responses:
        200:
          description: OK
        400:
          description: "Invalid parameter"
        401:
          description: "Authentication failed"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"

#路径通用参数
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: 地域ID