swagger: "2.0"
definitions:
  ipResource:
    type: object
    x-jdcloud-module: baseanti
    properties:
      ip:
        type: string
        description: 公网IP地址
      bandwidth:
        type: integer
        description: 带宽上限，单位Mbps
      safeStatus:
        type: integer
        description: 安全状态，0->安全 1->清洗 2->黑洞