swagger: "2.0"
definitions:
  ipResourceInfo:
    type: object
    x-jdcloud-module: baseanti
    properties:
      ip:
        type: string
        description: 公网IP地址
      safeStatus:
        type: integer
        description: 安全状态，0->安全 1->清洗 2->黑洞
      region:
        type: string
        description: 地域，cn-north-1、cn-south-1、cn-east-1、cn-east-2
      blackHoleThreshold:
        type: integer
        format: int64
        description: 黑洞阈值，单位bps
      cleanThresholdBps:
        type: integer
        format: int64
        description: 触发清洗的流量速率，单位bps
      cleanThresholdPps:
        type: integer
        format: int64
        description: 触发清洗的包速率，单位pps
