swagger: "2.0"
info:
  version: "v1"
  title: TOPIC相关 API
  description: 流数据总线topic相关信息接口

basePath: /regions/{regionId} 

paths:
  "/topicList":
  ###################### 查询topic接口 ######################
    get:
      description: "查询topic列表，返回topic的集合"
      operationId: getTopicList
      parameters:
        - name: keyword
          in: query
          type: string
          required: false
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  topic:
                    type: array
                    items:
                      type: object
                      $ref: "../model/topicListInfo.yaml#/definitions/topicListInfo"
              requestId:
                type: string
        401:
          description: ERROR
          
  "/topic":
  ###################### 创建topic接口 ######################
    post:
      description: 创建topic时，topicModel中只需要传topic参数，另外两个参数可为空
      operationId: addTopic
      parameters:
        - name: topicModel
          in: body
          required: true
          description: 示例：{"topicModel":{"topic":{"archived":0,"id":"","name":"create","remark":"备注","shardNum":1,"partitionNum":2,"lifecycle":3}}}
          schema:
            $ref: "../model/addOrUpdateTopic.yaml#/definitions/topicModel"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    description: "状态信息"
              requestId:
                type: string
        400:
          description: ERROR
                
  ###################### 更新topic接口 ######################
    put:
      description: 此接口可以用来更新主题，创建归档，修改归档，删除归档，传入不同的参数可以实现不同的功能。修改归档只需要修改相应归档的参数，删除归档只需要把归档参数置为空即可
      operationId: updateTopic
      parameters:
        - name: topicModel
          in: body
          required: true
          description: 当更新主题时只需要修改topicModel中的topic中的属性即可；创建归档需要指定target以及归档的目的地(mysql,京东云 Elasticsearch,对象存储,数据计算服务)参数
          schema:
            $ref: "../model/addOrUpdateTopic.yaml#/definitions/topicModel"
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    description: "状态信息"
              requestId:
                type: string
        400:
          description: ERROR
###################### 删除topic接口 ######################
    delete:
      description: "删除topic"
      operationId: deleteTopic
      parameters:
        - name: name
          in: query
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  status:
                    type: boolean
                  message:
                    type: string
                    description: "状态信息"
              requestId:
                type: string
        404:
          description: NOT FOUND
  ###################### 查看指定主题 ######################
    get:
      description: "查询指定主题,如果已归档会返回归档信息"
      operationId: describeTopic
      parameters:
        - name: name
          in: query
          required: true
          type: string
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                    topic:
                      type: object
                      $ref: "../model/addOrUpdateTopic.yaml#/definitions/topicModel"
              requestId:
                type: string
        404:
          description: NOT FOUND
                                
#路径通用参数
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: 地域ID