swagger: "2.0"
definitions:
  okInfo:
    x-jdcloud-module: streamcomputer
    title: okInfo
    type: object
    properties:
      status:
        type: boolean
      message: 
        type: string
        description: "状态信息"