swagger: "2.0"
definitions:
  os:
    x-jdcloud-module: cps
    title: os
    type: object
    properties:
      osTypeId:
        type: string
        description: 操作系统系统类型ID
      osName:
        type: string
        description: 操作系统系统名称, 如 Ubuntu 16.04(x86_64)
      osType:
        type: string
        description: 操作系统类型, 如 ubuntu/centos
      osVersion:
        type: string
        description: 操作系统版本, 如 14.04/16.04
      deviceType:
        type: string
        description: 实例类型, 如 cps.c.normal, 
