swagger: "2.0"
info:
  version: "v1"
  title: 云物理服务器
  description: 云物理服务器地域操作相关的接口

paths:
  "/regions":
    ###################### 查询云物理服务器地域列表 ######################
    get:
      description: "查询云物理服务器地域列表"
      operationId: describeRegiones
      responses:
        200:
          description: OK
          schema:
            type: object
            properties:
              result:
                properties:
                  regions:
                    type: array
                    items:
                      $ref: "../model/Region.yaml#/definitions/region"
              requestId:
                type: string
        400:
          description: "Bad request"
        404:
          description: "Not found"
        500:
          description: "Internal server error"
        503:
          description: "Service unavailable"