swagger: "2.0"
info:
  version: "v1"
  title: 配额
  description: k8s 集群配额相关接口

basePath: /regions/{regionId}

paths:
  "/quotas":
    ###################### 查询Quota ######################
    get:
      description: "查询(k8s 集群)配额"
      operationId: describeQuotas
      x-jdcloud-internal: false
      parameters:
        - name: filters
          in: query
          type: array
          items:
            $ref: "../../common/model/Filter.yaml#/definitions/filter"
          description: | 
            resourceTypes - 资源类型，暂时只支持[kubernetes]
      responses:
        200:
          description: OK
          schema:
            properties:
              result:
                properties:
                  quotas:
                    type: array
                    description: 配额列表
                    items:
                      $ref: "../model/Quota.yaml#/definitions/quota"
              requestId:
                type: string

    ###################### 修改Quota ######################
    patch:
      description: "修改(k8s 集群)配额，内部接口"
      operationId: modifyQuota
      x-jdcloud-internal: true
      parameters:
        - name: resourceType
          in: query
          type: string
          description: 资源类型[kubernetes]
        - name: limit
          in: query
          type: integer
          description: 配额上限
      responses:
        200:
          description: OK

#路径通用参数
parameters:
  regionId:
    name: regionId
    in: path
    required: true
    type: string
    description: Region ID