swagger: "2.0"
definitions:
  ag:
    x-jdcloud-module: vm
    properties:
      name:
        type: string
        description: 高可用组名称
      id:
        type: string
        description: 高可用组id
#      description:
#        type: string
#        description: 可用组id
#      agType:
#        type: string
#        description: 可用区类型，支持compute/container
#      instanceTemplateId:
#        type: string
#        description: 启动模板的Id
#      azs:
#        type: array
#        items:
#          type: string
#        description: 可用区域
#      count:
#        type: integer
#        description: 实例的数量
#      autoScaling:
#        type: boolean
#        description: 是否开启自动伸缩