swagger: "2.0"
definitions:
  imageConstraint:
    x-jdcloud-module: vm
    properties:
      imageId:
        type: string
        description: 镜像ID
      imageInstanceTypeConstraint:
        description: 使用镜像创建实例的规格限制
        $ref: "#/definitions/imageInstanceTypeConstraint"
  imageInstanceTypeConstraint:
    x-jdcloud-module: vm
    properties:
      constraintsType:
        description: 限制类型。取值：excludes：不支持的实例类型；includes：支持的实例类型。
        type: string
      instanceTypes:
        description: 实例规格列表
        type: array
        items:
          type: string
