swagger: "2.0"
definitions:
  instanceNetworkInterfaceAttachment:
    x-jdcloud-module: vm
    properties:
      deviceIndex:
        type: integer
        description: 设备Index
      autoDelete:
        type: boolean
        description: 指明删除实例时是否删除网卡，默认true；当前只能是true
      networkInterface:
        $ref: "./InstanceNetworkInterface.yaml#/definitions/instanceNetworkInterface"
        description: 网卡接口规范
