swagger: "2.0"
definitions:
  instanceTemplateData:
    x-jdcloud-module: vm
    properties:
      instanceType:
        type: string
        description: 实例规格
      vpcId:
        type: string
        description: 主网卡所属VPC的ID
      imageId:
        type: string
        description: 镜像ID
      includePassword:
        type: boolean
        description: 启动模板中是否包含自定义密码，true：包含密码，false：不包含密码
      systemDisk:
        $ref: "./InstanceTemplateDiskAttachment.yaml#/definitions/instanceTemplateDiskAttachment"
        description: 系统盘信息
      dataDisks:
        type: array
        items:
          $ref: "./InstanceTemplateDiskAttachment.yaml#/definitions/instanceTemplateDiskAttachment"
        description: 数据盘信息，本地盘(local类型)做系统盘的云主机可挂载8块数据盘，云硬盘(cloud类型)做系统盘的云主机可挂载7块数据盘。
      primaryNetworkInterface:
        $ref: "./InstanceTemplateNetworkInterfaceAttachmentSpec.yaml#/definitions/instanceTemplateNetworkInterfaceAttachmentSpec"
        description: 主网卡信息
      elasticIp:
        $ref: "./InstanceTemplateElasticIp.yaml#/definitions/instanceTemplateElasticIp"
        description: 主网卡主IP关联的弹性IP规格
      keyNames:
        type: array
        items:
          type: string
        minItems: 1
        description: 密钥对名称；当前只支持一个