swagger: "2.0"
definitions:
  instanceNetworkAttribute:
    x-jdcloud-module: vm
    properties:
      networkInterfaceId:
        type: string
        description: 弹性网卡ID
      autoDelete:
        type: boolean
        description: 随主机自动删除，默认为False
