swagger: "2.0"
definitions:
  instancePrivateIpAddress:
    x-jdcloud-module: vm
    properties:
      instanceId:
        type: string
        description: 云主机ID
      privateIpAddress:
        type: string
        description: 主网卡内网主IP地址