swagger: "2.0"
definitions:
  instanceNetworkInterface:
    x-jdcloud-module: vm
    properties:
      networkInterfaceId:
        type: string
        description: 弹性网卡ID
      macAddress:
        type: string
        description: 以太网地址
      vpcId:
        type: string
        description: 虚拟网络ID
      subnetId:
        type: string
        description: 子网ID
      securityGroups:
        type: array
        items:
          $ref: "./SecurityGroupSimple.yaml#/definitions/securityGroupSimple"
          description: 安全组列表
      sanityCheck:
        type: integer
        description: 源和目标IP地址校验，取值为0或者1
      primaryIp:
        $ref: "../../vpc/model/NetworkInterfacePrivateIp.yaml#/definitions/networkInterfacePrivateIp"
        description: 网卡主IP
      secondaryIps:
        type: array
        description: 网卡辅IP
        items:
          $ref: "../../vpc/model/NetworkInterfacePrivateIp.yaml#/definitions/networkInterfacePrivateIp"
