swagger: "2.0"
definitions:
  instanceTypeState:
    x-jdcloud-module: vm
    properties:
      az:
        type: string
        description: 可用区
      inStock:
        type: boolean
        description: 可售卖情况，true:可售卖、false:已售罄不可用
