swagger: "2.0"
definitions:
  instance:
    x-jdcloud-module: vm
    title: Instance
    type: object
    properties:
      instanceId:
        type: string
        description: 云主机ID
      instanceName:
        type: string
        description: 云主机名称
      instanceType:
        type: string
        description: 实例规格
      vpcId:
        type: string
        description: 主网卡所属VPC的ID
      subnetId:
        type: string
        description: 主网卡所属子网的ID
      privateIpAddress:
        type: string
        description: 主网卡主IP地址
      elasticIpId:
        type: string
        description: 主网卡主IP绑定弹性IP的ID
      elasticIpAddress:
        type: string
        description: 主网卡主IP绑定弹性IP的地址
      status:
        type: string
        description: 云主机状态，<a href="https://www.jdcloud.com/help/detail/3869/isCatalog/1">参考云主机状态</a>
      description:
        type: string
        description: 云主机描述
      imageId:
        type: string
        description: 镜像ID
      systemDisk:
        $ref: "./InstanceDiskAttachment.yaml#/definitions/instanceDiskAttachment"
        description: 系统盘配置
      dataDisks:
        type: array
        items:
          $ref: "./InstanceDiskAttachment.yaml#/definitions/instanceDiskAttachment"
        description: 数据盘配置
      primaryNetworkInterface:
        $ref: "./InstanceNetworkInterfaceAttachment.yaml#/definitions/instanceNetworkInterfaceAttachment"
        description: 主网卡配置
      secondaryNetworkInterfaces:
        type: array
        items:
          $ref: "./InstanceNetworkInterfaceAttachment.yaml#/definitions/instanceNetworkInterfaceAttachment"
        description: 辅助网卡配置
      launchTime:
        type: string
        format: date-time
        description: 创建时间
      az:
        type: string
        description: 云主机所在可用区
      keyNames:
        type: array
        items:
          type: string
        minItems: 1
        description: 密钥对名称
      charge:
        $ref: "../../charge/model/Charge.yaml#/definitions/charge"
        description: 计费信息
      ag:
        $ref: "./Ag.yaml#/definitions/ag"
        description: 高可用组，如果创建云主机使用了高可用组，此处可展示高可用组名称
      faultDomain:
        type: string
        description: 高可用组中的错误域
      tags:
        type: array
        items:
          $ref: "./Tag.yaml#/definitions/tag"
        description: Tag信息
