swagger: "2.0"
definitions:
  instanceSpec:
    x-jdcloud-module: vm
    required:
      - name
    properties:
      agId:
        type: string
        description: 高可用组Id。指定了此参数后，只能通过高可用组关联的实例模板创建虚机，并且实例模板中的参数不可覆盖替换。实例模板以外的参数还可以指定。
      instanceTemplateId:
        type: string
        description: 实例模板id，如果没有使用高可用组，那么对于实例模板中没有的信息，需要使用创建虚机的参数进行补充，或者选择覆盖启动模板中的参数。
      az:
        type: string
        description: 云主机所属的可用区。
      instanceType:
        type: string
        description: 实例规格。可查询<a href="https://www.jdcloud.com/help/detail/2901/isCatalog/1">DescribeInstanceTypes</a>接口获得指定地域或可用区的规格信息。
      imageId:
        type: string
        description: 镜像ID。可查询<a href="https://www.jdcloud.com/help/detail/2874/isCatalog/1">DescribeImages</a>接口获得指定地域的镜像信息。
      name:
        type: string
        description: 云主机名称，<a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1">参考公共参数规范</a>。
      password:
        type: string
        description: 密码，<a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1">参考公共参数规范</a>。
      keyNames:
        type: array
        items:
          type: string
        description: 密钥对名称，当前只支持传入一个。
      elasticIp:
        $ref: "../../vpc/model/ElasticIpSpec.yaml#/definitions/elasticIpSpec"
        description: 主网卡主IP关联的弹性IP规格
      primaryNetworkInterface:
        $ref: "./InstanceNetworkInterfaceAttachmentSpec.yaml#/definitions/instanceNetworkInterfaceAttachmentSpec"
        description: 主网卡配置信息
      systemDisk:
        $ref: "./InstanceDiskAttachmentSpec.yaml#/definitions/instanceDiskAttachmentSpec"
        description: 系统盘配置信息
      dataDisks:
        type: array
        items:
          $ref: "./InstanceDiskAttachmentSpec.yaml#/definitions/instanceDiskAttachmentSpec"
        description: 数据盘配置信息，本地盘(local类型)做系统盘的云主机可挂载8块数据盘，云硬盘(cloud类型)做系统盘的云主机可挂载7块数据盘。
      charge:
        $ref: "../../charge/model/ChargeSpec.yaml#/definitions/chargeSpec"
        description: |
          计费配置
          云主机不支持按用量方式计费，默认为按配置计费。
          打包创建数据盘的情况下，数据盘的计费方式只能与云主机保持一致。
          打包创建弹性公网IP的情况下，若公网IP的计费方式没有指定为按用量计费，那么公网IP计费方式只能与云主机保持一致。
      description:
        type: string
        description: 主机描述，<a href="https://www.jdcloud.com/help/detail/3870/isCatalog/1">参考公共参数规范</a>。
