swagger: "2.0"
definitions:
  instanceTemplateDiskSpec:
    x-jdcloud-module: vm
    properties:
      diskType:
        type: string
        enum:
          - "ssd"
          - "premium-hdd"
        description: 云硬盘类型，取值为 ssd 或 premium-hdd
      diskSizeGB:
        type: integer
        description: 云硬盘大小，单位为 GiB；ssd 类型取值范围[20,1000]GB，步长为10G，premium-hdd 类型取值范围[20,3000]GB，步长为10G
      snapshotId:
        type: string
        description: 用于创建云硬盘的快照ID