swagger: "2.0"
definitions:
  instanceTemplate:
    x-jdcloud-module: vm
    properties:
      id:
        type: string
        description: 启动模板ID
      name:
        type: string
        description: 启动模板名称
      description:
        type: string
        description: 启动模板描述
      instanceTemplateData:
        $ref: "./InstanceTemplateData.yaml#/definitions/instanceTemplateData"
        description: 启动模板的数据
      ags:
        type: array
        items:
          $ref: "./Ag.yaml#/definitions/ag"
        description: 关联的高可用组(ag)信息
      createdTime:
        type: string
        format: date-time
        description: 创建时间