swagger: "2.0"
definitions:
  instanceTemplateNetworkInterfaceSpec:
    x-jdcloud-module: vm
    required:
      - subnetId
    properties:
      subnetId:
        type: string
        description: 子网ID
      securityGroups:
        type: array
        items:
          type: string
        description: 安全组ID列表
      sanityCheck:
        type: integer
        description: PortSecurity，取值为0或者1，默认为1