swagger: "2.0"
definitions:
  keypair:
    x-jdcloud-module: vm
    properties:
      keyName:
        type: string
        description: 密钥对名称
      keyFingerprint:
        type: string
        description: 密钥对的指纹，根据 RFC4716 定义的公钥指纹格式，采用 MD5 信息摘要算法。