swagger: "2.0"
definitions:
  localDisk:
    x-jdcloud-module: vm
    description: 描述实例的本地磁盘
    type: object
    properties:
      diskType:
        type: string
        description: 磁盘类型，取值范围{premium-hdd, ssd}
      diskSizeGB:
        type: integer
        description: 磁盘大小
