swagger: "2.0"
definitions:
  quota:
    x-jdcloud-module: vm
    properties:
      resourceType:
        type: string
        description: 资源类型[instance，keypair，image，instanceTemplate]
      limit:
        type: integer
        description: 配额上限
      used:
        type: integer
        description: 已用配额
