swagger: "2.0"
definitions:
  securityGroupSimple:
    x-jdcloud-module: vm
    description: 描述实例绑定的安全组
    type: object
    properties:
      groupId:
        type: string
        description: 安全组ID
      groupName:
        type: string
        description: 安全组名称
